### PR TITLE
Provide orphan rules compatible impls

### PR DESCRIPTION
**Pull request by DJMcNab**

### CODE REVIEW

**Comment by Philipp-M** [comment]
Should, we wait with this until after #310 is merged, or should we include that as well?

**Comment by DJMcNab** [comment]
I think this is more controversial and should wait

**Comment by Philipp-M** [comment]
I was so free to rebase this onto #310, hope you don't mind, this does have problems anyway as you should see in the failing tests.

I don't think it's too controversial in the targeted result, but I agree, with the way achieving it (adding an additional generic Marker). But I'm at least right now also not sure how to achieve it otherwise...

**Comment by DJMcNab** [comment]
Ahah, so the issue arises because the `message` function isn't constrained by the context type. That's rather unfortunate, but is effectively a test-specific issue.

**Pull request closed without merging**
